"""empty message

Revision ID: 17d6d949de06
Revises: 
Create Date: 2023-09-17 03:23:04.084506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d6d949de06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_index(op.f('ix_countries_country_id'), 'countries', ['country_id'], unique=False)
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_index(op.f('ix_cities_city_id'), 'cities', ['city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_city_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_countries_country_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
